### ISSUE TITLE
shared settings

### ISSUE THREAD

**Issue by aliirz** [JakeGinnivan/SettingsProvider.net#2]
Hello there. I simply love this package. I was wondering if there is any way to share the created settings between two projects?

I want to be able to create the settings from a wpf app and then have a windows service read from them. Is this possible?

Thanks

**Comment by JakeGinnivan** [comment]
Hey

You will have to provide a custom settings store, have a look at https://github.com/JakeGinnivan/SettingsProvider.net/blob/master/src/SettingsProviderNet/IsolatedStorageSettingsStore.cs

Simply inherit from `JsonSettingsStoreBase` then implement your own logic to save to a shared location. You then just pass this settings store into the `SettingsProvider` when it is newed up

**Comment by JakeGinnivan** [comment]
I am about to release v2 which will make this really easy. Simple use `new SettingsProvider(new RoamingAppDataStorage("MyAppName"))` and then share the settings class between the two projects
