### ISSUE TITLE
Settings not written

### ISSUE THREAD

**Issue by aliirz** [JakeGinnivan/SettingsProvider.net#3]
Hi Again

I am using the nuget in a class library i call to save settings. However i can see the file being created but it appears to be empty and when I try to read it, i get empty values. What am I doing wrong?

Please help.

**Comment by JakeGinnivan** [comment]
Not sure.

I am thinking about changing this to a library rather than just putting the code into your project. This will make it easier to hide internals and make it easier to get started.

Can you paste some code so I can see what you are doing?

**Comment by aliirz** [comment]
Hi @JakeGinnivan  thanks for replying. These are the following two methods I am using in order o save and retrieve the settings:

``` c#
 public ClientSettings GetClientSettings()
 {
            SettingsProvider provider = new SettingsProvider();
            return provider.GetSettings<ClientSettings>(false);   //I cant seem to call the Load Method for some reason. I think its no longer supported.
 }
```

``` c#
public bool SaveClientSettings(ClientSettings settings)
{
            try
            {
                provider.SaveSettings<ClientSettings>(settings);
            }
            catch (Exception ex)
            {
                return false;
            }
            return true;
}
```

And this is what my ClientSettings class looks like:

``` c#
 [Serializable]
    public class ClientSettings
    {
        public int orgID { get; set; }
        public string username { get; set; }
    }
```

I will really appreciate if you can help with this. Thanks

**Comment by aliirz** [comment]
This is how client settings look like when created, I always setup the parameters but notice how its 0 kb. I have opened it and tried reading it as well via the above code but i can never retrieve the settings...

![clientsettings](https://f.cloud.github.com/assets/743962/1137886/93cfea38-1c69-11e3-8730-1896d0691728.PNG)

**Comment by JakeGinnivan** [comment]
The class doesn't have to be marked as serializable. 

Interesting. That looks like a bug (I have only reused the settings provider rather than newing it up every time). I think it is related to that. Try making it a static property and ill look into it over the weekend

**Comment by aliirz** [comment]
Thanks @JakeGinnivan  I will check by creating it as a static property.

**Comment by aliirz** [comment]
Still not working :( This is how i have implemented the static instance of the provider now:

``` c#
public static SettingsProvider _settingsProvider;

static SettingsService()
{
            _settingsProvider = new SettingsProvider();
}

public ClientSettings GetClientSettings()
{
           return _settingsProvider.GetSettings<ClientSettings>();
}

public bool SaveClientSettings(ClientSettings settings)
{
    try
    {
           _settingsProvider.SaveSettings<ClientSettings>(settings);
    }
    catch (Exception ex)
    {
           return false;
    }
          return true;
 }
```

**Comment by JakeGinnivan** [comment]
Try uninstalling, deleting the classes which are put into your project, then reinstalling. I fixed a bug a few weeks ago which caused things not to write properly

I am working on v2 which will be a class library, but will be a few more days

**Comment by aliirz** [comment]
Ok I will add directly from the github repo rather than using the nuget package.

**Comment by aliirz** [comment]
Sadly I got the same result :( I can see the created file but its empty, no settings inside it.

**Comment by aliirz** [comment]
Hey @JakeGinnivan  any updates on this?

Regards

**Comment by JakeGinnivan** [comment]
@aliirz I know it has been ages, I have just finished overhauling the internals and converting this to a class library in prep for v2. Once its released if you still need this let me know how you go
